"""Convert LAWA region boundaries (WKT, from mapservice/boundaryforNZ) to GeoJSON.

Input : data/raw/boundaries/lawa_regions_raw.json  (LAWA API snapshot, CC BY 4.0)
Output: data/ref/boundaries_regions.geojson       (6 project councils, full detail)

The simplified variant is produced once with mapshaper (see Makefile target
`boundaries`); both live in data/ref/ as committed reference data for the
site map — they are NOT regenerated by `make data` (data/raw is gitignored).

LAWA shapes are single-ring POLYGONs in lon/lat (WGS84), which map directly to
GeoJSON [lon, lat] rings. No holes/multipolygons are present in the snapshot.
"""
from __future__ import annotations

import json
import os
import re
import sys

# 6 project councils → (LAWA code, LAWA name, Stats NZ region key)
TARGETS = [
    ("AUCKLAND", "Auckland region", "auckland"),
    ("WAIKATO", "Waikato region", "waikato"),
    ("HAWKESBAY", "Hawke's Bay region", "hawkes_bay"),
    ("CANTERBURY", "Canterbury region", "canterbury"),
    ("OTAGO", "Otago region", "otago"),
    ("SOUTHLAND", "Southland region", "southland"),
]
TARGET_CODES = {t[0] for t in TARGETS}


def parse_wkt_polygon(wkt: str) -> list[list[list[float]]]:
    """Parse a WKT POLYGON/MULTIPOLYGON string → GeoJSON polygon(s) [lon, lat]."""
    wkt = wkt.strip()
    if wkt.startswith("MULTIPOLYGON"):
        # MULTIPOLYGON (((...)), ((...)))
        polys: list[list[list[float]]] = []
        # split at ')), ((' boundaries between polygons
        body = wkt[len("MULTIPOLYGON"):].strip()
        inner = body[body.index("("):]  # includes leading "(" of first poly
        # find all "((" ... "))" groups
        for m in re.finditer(r"\(\(([^()]*)\)\)", inner):
            rings = _parse_rings(m.group(1))
            polys.append(rings)
        return polys
    if wkt.startswith("POLYGON"):
        body = wkt[len("POLYGON"):].strip()
        rings_body = body[body.index("(") + 1: body.rindex(")")]
        # rings separated by "), ("
        rings = _parse_rings(rings_body)
        return [rings]
    raise ValueError(f"unsupported WKT: {wkt[:40]}")


def _parse_rings(rings_text: str) -> list[list[list[float]]]:
    rings: list[list[list[float]]] = []
    for ring_txt in re.split(r"\)\s*,\s*\(", rings_text.strip()):
        ring_txt = ring_txt.strip().strip("()").strip()
        if not ring_txt:
            continue
        coords: list[list[float]] = []
        for pair in re.findall(r"([-\d.]+)\s+([-\d.]+)", ring_txt):
            coords.append([float(pair[0]), float(pair[1])])
        if coords:
            rings.append(coords)
    return rings


def main() -> int:
    raw_path = "data/raw/boundaries/lawa_regions_raw.json"
    out_path = "data/ref/boundaries_regions.geojson"
    raw = json.load(open(raw_path, encoding="utf-8"))

    features = []
    for feat in raw:
        if feat["Code"] not in TARGET_CODES:
            continue
        try:
            polygons = parse_wkt_polygon(feat["Shape"])
        except ValueError as e:
            print(f"skip {feat['Code']}: {e}", file=sys.stderr)
            continue
        region_key = next(t[2] for t in TARGETS if t[0] == feat["Code"])
        geometry = {"type": "Polygon" if len(polygons) == 1 else "MultiPolygon",
                    "coordinates": polygons[0] if len(polygons) == 1 else polygons}
        features.append({
            "type": "Feature",
            "properties": {
                "code": feat["Code"],          # LAWA zone code (uppercase)
                "name": feat["Name"],          # LAWA zone name
                "region": region_key,          # project region key (snake_case)
            },
            "geometry": geometry,
        })

    fc = {
        "type": "FeatureCollection",
        "name": "nz_regional_boundaries_6councils",
        "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}},
        "source": "LAWA mapservice/boundaryforNZ (CC BY 4.0), derived from Stats NZ regional council boundaries",
        "fetched_utc": raw[0].get("fetched_utc", "2026-08-30"),
        "features": features,
    }
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(fc, f, ensure_ascii=False)
    print(f"wrote {out_path}: {len(features)} features, {os.path.getsize(out_path) // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
